name = "Tandoori"
license = "MIT"
licenselink = "https://github.com/gnappuraz/tandoori-hugo/blob/master/LICENSE"
description = "A minilastic blog theme"
tags = ["blog", "minimalist", "minimal", "responsive", "seo"]
features = ["blog", "themes", "minimal", "responsive"]
min_version = 0.59.1

[author]
    name = "Gnappuraz"

[original]
    author =  "halogenica"
    hhomepage = "http://halogenica.net"
    repo = "https://github.com/halogenica/Hugo-BeautifulHugo"
